name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ARM64 Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- FIX: Build and export the raw release files ---
      - name: Build ARM64 release files
        uses: docker/build-push-action@v5
        with:
          context: .
          # Target the final stage of our Dockerfile
          target: release_holder
          # We are building for linux/arm64
          platforms: linux/arm64
          # Export the contents of the final image stage to a local directory
          outputs: type=local,dest=./release-output

      # --- FIX: Create the tarball from the exported files ---
      - name: Create release tarball
        run: |
          cd ./release-output/release
          tar -czf ../../radio-backend-release.tar.gz .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: radio-backend-release
          # The tarball is now in the root of the workspace
          path: radio-backend-release.tar.gz

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: radio-backend-release

      - name: Copy release to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # --- FIX: Use a specific filename instead of a wildcard ---
          source: "radio-backend-release.tar.gz"
          target: "/tmp"

      - name: Deploy and Restart on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # --- FIX: Pass secrets as environment variables for better security ---
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
            PHX_HOST: ${{ secrets.PHX_HOST }}
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            
            RELEASE_DIR="/var/www/radio_backend"
            RELEASE_TAR="/tmp/radio-backend-release.tar.gz"
            
            echo "-----> Preparing deployment directory"
            sudo rm -rf $RELEASE_DIR/*
            sudo mkdir -p $RELEASE_DIR
            sudo chown ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} $RELEASE_DIR
            
            echo "-----> Unpacking new release"
            sudo tar -xzf $RELEASE_TAR -C $RELEASE_DIR
            sudo rm $RELEASE_TAR
            
            echo "-----> Running database migrations"
            # --- FIX: Add parentheses to the function call ---
            $RELEASE_DIR/bin/radio_backend eval "RadioBackend.Release.migrate()"

            echo "-----> Restarting application service"
            sudo systemctl restart radio_backend
            
            echo "-----> Deployment successful!"
