name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Elixir Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3'

      - name: Cache Elixir dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/assets/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install all dependencies
        run: |
          mix deps.get --only prod
          npm install --prefix ./assets

      - name: Compile assets and build release
        env:
          MIX_ENV: prod
        run: |
          mix esbuild.install --if-missing
          mix assets.deploy
          mix release

      # --- THIS IS THE FINAL, CORRECTED TARBALL CREATION ---
      - name: Create complete release tarball
        run: |
          # Navigate into the root of the generated release structure
          cd _build/prod/rel/radio_backend
          
          # This command archives the essential directories (bin, lib, releases)
          # that make up a complete, runnable release.
          tar -czf "radio_backend-release.tar.gz" bin lib releases erts-*

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: radio-backend-release
          path: _build/prod/rel/radio_backend/*.tar.gz

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: radio-backend-release

      - name: Copy release to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.tar.gz"
          target: "/tmp"

      # --- THIS IS THE NEW DIAGNOSTIC STEP ---
      - name: Unpack and Verify on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clean out the old release to ensure a fresh state
            sudo rm -rf /var/www/radio_backend/*
            sudo mkdir -p /var/www/radio_backend
            sudo chown ${{ secrets.SSH_USERNAME }}:${{ secrets.SSH_USERNAME }} /var/www/radio_backend

            # Unpack the release
            sudo tar -xzf /tmp/*.tar.gz -C /var/www/radio_backend/

            # --- THIS IS THE MOST IMPORTANT PART ---
            # Let's see what is actually inside the directory after unpacking
            echo "--- Verifying unpacked contents of /var/www/radio_backend/ ---"
            ls -lA /var/www/radio_backend/
            
            # Let's also check if the 'bin' directory exists and what's inside it
            echo "--- Verifying contents of /var/www/radio_backend/bin/ ---"
            # This will error if the directory doesn't exist, which is useful info
            ls -lA /var/w/radio_backend/bin/ || echo "--> The bin directory was NOT found."
            
            # ----------------------------------------

            # The rest of the script is disabled for this test.
            echo "--- Debugging complete. Please post the full output of this step. ---"
