name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Elixir Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '27.3'

      # Cache dependencies to speed up future builds
      - name: Cache Elixir dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/assets/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install all dependencies
        run: |
          mix deps.get --only prod
          npm install --prefix ./assets

      - name: Compile assets and build release
        env:
          MIX_ENV: prod
        run: |
          mix esbuild.install --if-missing
          mix assets.deploy
          mix release
      - name: Create release tarball
        run: |
          cd _build/prod/rel/radio_backend/releases
          RELEASE_VERSION=$(ls | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Found release version: ${RELEASE_VERSION}"
          tar -czf "../radio_backend-${RELEASE_VERSION}.tar.gz" "${RELEASE_VERSION}"
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: radio-backend-release
          # The path to the generated .tar.gz file
          path: _build/prod/rel/radio_backend/*.tar.gz

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: radio-backend-release

      # --- THIS IS THE NEW, CRUCIAL DEBUGGING STEP ---
      - name: Inspect downloaded artifact
        run: |
          echo "Listing contents of the downloaded tarball:"
          tar -tvf *.tar.gz

      - name: Deploy and Unpack on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # For now, we are just copying the file.
            # We will add the rest of the commands back after we know the structure.
            echo "File transfer complete. Next step is to fix the unpack command."
